[package]
name = "rammer"
version = "0.1.0"
authors = ["Dalton Maahs <dalton.maahs@yourbind.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.7.1"
